-- MySQL Script generated by MySQL Workbench
-- 07/25/18 11:18:49
-- Model: Modelo Piloto    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema piloto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema piloto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `piloto` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `piloto` ;

-- -----------------------------------------------------
-- Table `piloto`.`tbCorretora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbCorretora` (
  `idCorretora` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `RazaoSocial` VARCHAR(100) NULL COMMENT '',
  `Fantasia` VARCHAR(45) CHARACTER SET 'big5' NULL COMMENT '',
  `Cnpj` VARCHAR(20) NULL COMMENT '',
  `Inscricao` VARCHAR(45) NULL COMMENT '',
  `Endereco` VARCHAR(100) NULL COMMENT '',
  `Bairro` VARCHAR(50) NULL COMMENT '',
  `Cidade` VARCHAR(45) NULL COMMENT '',
  `Uf` VARCHAR(2) NULL COMMENT '',
  `Cep` VARCHAR(10) NULL COMMENT '',
  `Email` VARCHAR(100) NULL COMMENT '',
  `Telefone` VARCHAR(45) NULL COMMENT '',
  `Contato` VARCHAR(45) NULL COMMENT '',
  `Celular` VARCHAR(45) NULL COMMENT '',
  `Site` VARCHAR(50) NULL COMMENT '',
  `tbColaborador_idColaborador` INT NOT NULL COMMENT '',
  `tbColaborador_id_Corretora` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCorretora`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piloto`.`tbFuncao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbFuncao` (
  `idFuncao` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Funcao` VARCHAR(50) NULL COMMENT '',
  `Nivel` INT NULL COMMENT '',
  PRIMARY KEY (`idFuncao`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piloto`.`tbColaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbColaborador` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_Corretora` INT UNSIGNED NOT NULL COMMENT '',
  `id_Funcao` INT NOT NULL COMMENT '',
  `Nome` VARCHAR(100) NOT NULL COMMENT '',
  `Cpf` VARCHAR(15) NULL COMMENT '',
  `Endereco` VARCHAR(100) NULL COMMENT '',
  `Bairro` VARCHAR(50) NULL COMMENT '',
  `Cidade` VARCHAR(50) NULL COMMENT '',
  `Uf` VARCHAR(2) NULL COMMENT '',
  `Cep` VARCHAR(10) NULL COMMENT '',
  `Telefone` VARCHAR(45) NULL COMMENT '',
  `Celular` VARCHAR(45) NULL COMMENT '',
  `Email` VARCHAR(45) NULL COMMENT '',
  `DataCadastro` DATETIME NULL COMMENT '',
  `Comissao` DECIMAL(9,3) NULL COMMENT '',
  `Estatus` INT NULL COMMENT '',
  PRIMARY KEY (`idColaborador`, `id_Corretora`, `id_Funcao`)  COMMENT '',
  INDEX `fk_tbColaborador_tbCorretora_idx` (`id_Corretora` ASC)  COMMENT '',
  INDEX `fk_tbColaborador_tbFuncao1_idx` (`id_Funcao` ASC)  COMMENT '',
  CONSTRAINT `fk_tbColaborador_tbCorretora`
    FOREIGN KEY (`id_Corretora`)
    REFERENCES `piloto`.`tbCorretora` (`idCorretora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbColaborador_tbFuncao1`
    FOREIGN KEY (`id_Funcao`)
    REFERENCES `piloto`.`tbFuncao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piloto`.`tbInvestidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbInvestidor` (
  `idInvestidor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_Corretora` INT UNSIGNED NOT NULL COMMENT '',
  `id_Colaborador` INT NOT NULL COMMENT '',
  `Nome` VARCHAR(100) NULL COMMENT '',
  `Cpf` VARCHAR(15) NULL COMMENT '',
  `Rg` VARCHAR(20) NULL COMMENT '',
  `Endereco` VARCHAR(150) NULL COMMENT '',
  `Bairro` VARCHAR(50) NULL COMMENT '',
  `Cidade` VARCHAR(50) NULL COMMENT '',
  `Uf` VARCHAR(2) NULL COMMENT '',
  `Cep` VARCHAR(10) NULL COMMENT '',
  `Email` VARCHAR(100) NULL COMMENT '',
  `Telefone` VARCHAR(15) NULL COMMENT '',
  `Celular` VARCHAR(15) NULL COMMENT '',
  `Modalidade` INT NULL COMMENT '',
  `Banco` DECIMAL(10,0) NULL COMMENT '',
  `Agencia` VARCHAR(10) NULL COMMENT '',
  `Operacao` VARCHAR(10) NULL COMMENT '',
  `Conta` VARCHAR(45) NULL COMMENT '',
  `TipoConta` VARCHAR(2) NULL COMMENT '',
  PRIMARY KEY (`idInvestidor`, `id_Corretora`, `id_Colaborador`)  COMMENT '',
  INDEX `fk_tbInvestidor_tbCorretora1_idx` (`id_Corretora` ASC)  COMMENT '',
  INDEX `fk_tbInvestidor_tbColaborador1_idx` (`id_Colaborador` ASC)  COMMENT '',
  CONSTRAINT `fk_tbInvestidor_tbCorretora1`
    FOREIGN KEY (`id_Corretora`)
    REFERENCES `piloto`.`tbCorretora` (`idCorretora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbInvestidor_tbColaborador1`
    FOREIGN KEY (`id_Colaborador`)
    REFERENCES `piloto`.`tbColaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piloto`.`tbLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbLogin` (
  `idLogin` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_Corretora` INT UNSIGNED NOT NULL COMMENT '',
  `id_Colaborador` INT NOT NULL COMMENT '',
  `id_Investidor` INT NOT NULL COMMENT '',
  `Perfil` INT NOT NULL COMMENT '',
  `Usuario` VARCHAR(45) NULL COMMENT '',
  `Senha` VARCHAR(45) NULL COMMENT '',
  `Email` VARCHAR(50) NULL COMMENT '',
  `Estatus` INT NULL COMMENT '',
  PRIMARY KEY (`idLogin`, `id_Corretora`, `id_Colaborador`, `id_Investidor`)  COMMENT '',
  INDEX `fk_tbLogin_tbCorretora1_idx` (`id_Corretora` ASC)  COMMENT '',
  INDEX `fk_tbLogin_tbColaborador1_idx` (`id_Colaborador` ASC)  COMMENT '',
  INDEX `fk_tbLogin_tbInvestidor1_idx` (`id_Investidor` ASC)  COMMENT '',
  CONSTRAINT `fk_tbLogin_tbCorretora1`
    FOREIGN KEY (`id_Corretora`)
    REFERENCES `piloto`.`tbCorretora` (`idCorretora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbLogin_tbColaborador1`
    FOREIGN KEY (`id_Colaborador`)
    REFERENCES `piloto`.`tbColaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbLogin_tbInvestidor1`
    FOREIGN KEY (`id_Investidor`)
    REFERENCES `piloto`.`tbInvestidor` (`idInvestidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piloto`.`tbDepSaq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbDepSaq` (
  `idDepSaq` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_Corretora` INT UNSIGNED NOT NULL COMMENT '',
  `id_Colaborador` INT NOT NULL COMMENT '',
  `id_Investidor` INT NOT NULL COMMENT '',
  `DataMov` DATETIME NULL COMMENT '',
  `TipoMov` VARCHAR(1) NULL COMMENT '',
  `Valor` REAL NULL COMMENT '',
  `Banco` DECIMAL(10,0) NULL COMMENT '',
  `Agencia` VARCHAR(10) NULL COMMENT '',
  `Operacao` VARCHAR(10) NULL COMMENT '',
  `Conta` VARCHAR(45) NULL COMMENT '',
  `TipoConta` VARCHAR(2) NULL COMMENT '',
  `Confirmado` TINYINT(1) NULL COMMENT '',
  `DataConfirmacao` DATETIME NULL COMMENT '',
  `Modalidade` INT NULL COMMENT '',
  PRIMARY KEY (`idDepSaq`, `id_Corretora`, `id_Colaborador`, `id_Investidor`)  COMMENT '',
  INDEX `fk_tbDepSaq_tbCorretora1_idx` (`id_Corretora` ASC)  COMMENT '',
  INDEX `fk_tbDepSaq_tbColaborador1_idx` (`id_Colaborador` ASC)  COMMENT '',
  INDEX `fk_tbDepSaq_tbInvestidor1_idx` (`id_Investidor` ASC)  COMMENT '',
  CONSTRAINT `fk_tbDepSaq_tbCorretora1`
    FOREIGN KEY (`id_Corretora`)
    REFERENCES `piloto`.`tbCorretora` (`idCorretora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbDepSaq_tbColaborador1`
    FOREIGN KEY (`id_Colaborador`)
    REFERENCES `piloto`.`tbColaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbDepSaq_tbInvestidor1`
    FOREIGN KEY (`id_Investidor`)
    REFERENCES `piloto`.`tbInvestidor` (`idInvestidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piloto`.`tbTrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbTrade` (
  `idTrade` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_Corretora` INT UNSIGNED NOT NULL COMMENT '',
  `id_Login` INT NOT NULL COMMENT '',
  `DataInicio` DATETIME NULL COMMENT '',
  `TipoInvestimento` INT NULL COMMENT '',
  `PercInvestido` DECIMAL(9,3) NULL COMMENT '',
  `DataFim` DATETIME NULL COMMENT '',
  `Resultado` DECIMAL(12,3) NULL COMMENT '',
  `PercComissao` DECIMAL(9,3) NULL COMMENT '',
  PRIMARY KEY (`idTrade`, `id_Corretora`, `id_Login`)  COMMENT '',
  INDEX `fk_tbTrade_tbCorretora1_idx` (`id_Corretora` ASC)  COMMENT '',
  INDEX `fk_tbTrade_tbLogin1_idx` (`id_Login` ASC)  COMMENT '',
  CONSTRAINT `fk_tbTrade_tbCorretora1`
    FOREIGN KEY (`id_Corretora`)
    REFERENCES `piloto`.`tbCorretora` (`idCorretora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbTrade_tbLogin1`
    FOREIGN KEY (`id_Login`)
    REFERENCES `piloto`.`tbLogin` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piloto`.`tbMovimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbMovimentacao` (
  `idMovimentacao` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_Corretora` INT UNSIGNED NOT NULL COMMENT '',
  `id_Colaborador` INT NOT NULL COMMENT '',
  `id_Investidor` INT NOT NULL COMMENT '',
  `id_Login` INT NOT NULL COMMENT '',
  `DataMov` DATETIME NULL COMMENT '',
  `CapitalInvestido` DECIMAL(12,2) NULL COMMENT '',
  `Resultado` DECIMAL(12,2) NULL COMMENT '',
  `CapitalBruto` DECIMAL(12,2) NULL COMMENT '',
  `Comissao` DECIMAL(9,3) NULL COMMENT '',
  `Deposito` DECIMAL(12,2) NULL COMMENT '',
  `CapitalLiquido` DECIMAL(12,2) NULL COMMENT '',
  PRIMARY KEY (`idMovimentacao`, `id_Corretora`, `id_Colaborador`, `id_Investidor`, `id_Login`)  COMMENT '',
  INDEX `fk_tbMovimentacao_tbCorretora1_idx` (`id_Corretora` ASC)  COMMENT '',
  INDEX `fk_tbMovimentacao_tbColaborador1_idx` (`id_Colaborador` ASC)  COMMENT '',
  INDEX `fk_tbMovimentacao_tbInvestidor1_idx` (`id_Investidor` ASC)  COMMENT '',
  INDEX `fk_tbMovimentacao_tbLogin1_idx` (`id_Login` ASC)  COMMENT '',
  CONSTRAINT `fk_tbMovimentacao_tbCorretora1`
    FOREIGN KEY (`id_Corretora`)
    REFERENCES `piloto`.`tbCorretora` (`idCorretora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbMovimentacao_tbColaborador1`
    FOREIGN KEY (`id_Colaborador`)
    REFERENCES `piloto`.`tbColaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbMovimentacao_tbInvestidor1`
    FOREIGN KEY (`id_Investidor`)
    REFERENCES `piloto`.`tbInvestidor` (`idInvestidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbMovimentacao_tbLogin1`
    FOREIGN KEY (`id_Login`)
    REFERENCES `piloto`.`tbLogin` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piloto`.`tbItemTrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piloto`.`tbItemTrade` (
  `idItemTrade` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_Trade` INT NOT NULL COMMENT '',
  `id_Corretora` INT UNSIGNED NOT NULL COMMENT '',
  `id_Investidor` INT NOT NULL COMMENT '',
  `VlInvestido` DECIMAL(12,2) NULL COMMENT '',
  `DataInicio` DATETIME NULL COMMENT '',
  `Resultado` DECIMAL(12,2) NULL COMMENT '',
  `DataFim` DATETIME NULL COMMENT '',
  `Comissao` DECIMAL(9,3) NULL COMMENT '',
  PRIMARY KEY (`idItemTrade`, `id_Trade`, `id_Corretora`, `id_Investidor`)  COMMENT '',
  INDEX `fk_tbTrade_has_tbInvestidor_tbInvestidor1_idx` (`id_Investidor` ASC)  COMMENT '',
  INDEX `fk_tbTrade_has_tbInvestidor_tbTrade1_idx` (`id_Trade` ASC, `id_Corretora` ASC)  COMMENT '',
  CONSTRAINT `fk_tbTrade_has_tbInvestidor_tbTrade1`
    FOREIGN KEY (`id_Trade` , `id_Corretora`)
    REFERENCES `piloto`.`tbTrade` (`idTrade` , `id_Corretora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbTrade_has_tbInvestidor_tbInvestidor1`
    FOREIGN KEY (`id_Investidor`)
    REFERENCES `piloto`.`tbInvestidor` (`idInvestidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
